
import os

# Auto-generated by setup_env.py

REPO_ROOT = r'/mnt/c/Users/Joacaldo/OneDrive - Universidad Católica de Chile/FrankPEPstein'
UTILITIES_DIR = r'/mnt/c/Users/Joacaldo/OneDrive - Universidad Católica de Chile/FrankPEPstein/utilities'
DB_DIR = r'/mnt/c/Users/Joacaldo/OneDrive - Universidad Católica de Chile/FrankPEPstein/DB'

# Tools
ADFR_BIN = r'/mnt/c/Users/Joacaldo/OneDrive - Universidad Católica de Chile/FrankPEPstein/utilities/ADFRsuite_x86_64Linux_1.0/bin'
CLICK_DIR = r'/mnt/c/Users/Joacaldo/OneDrive - Universidad Católica de Chile/FrankPEPstein/utilities/Click'
VINA_PATH = r'/mnt/c/Users/Joacaldo/OneDrive - Universidad Católica de Chile/FrankPEPstein/utilities/vina_1.2.4_linux_x86_64'

# Resources
DEFAULT_DB_PATH = os.path.join(REPO_ROOT, "DB", "filtered_DB_P5-15_R30_id10")
REDUCE_DICT_PATH = r'/mnt/c/Users/Joacaldo/OneDrive - Universidad Católica de Chile/FrankPEPstein/DB/reduce_wwPDB_het_dict.txt'

# Configuration
THREADS = 14
