
import os

# Auto-generated by setup_env.py (Dynamic Version)

# Determine Repo Root (Parent of 'scripts')
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPTS_DIR)

UTILITIES_DIR = os.path.join(REPO_ROOT, 'utilities')
DB_DIR = os.path.join(REPO_ROOT, 'DB')

# Tools
ADFR_BIN = os.path.join(UTILITIES_DIR, 'ADFRsuite_x86_64Linux_1.0', 'bin')
CLICK_DIR = os.path.join(UTILITIES_DIR, 'Click')
VINA_PATH = os.path.join(UTILITIES_DIR, 'vina_1.2.4_linux_x86_64')

# Resources
DEFAULT_DB_PATH = os.path.join(DB_DIR, "filtered_DB_P5-15_R30_id10")
REDUCE_DICT_PATH = os.path.join(DB_DIR, 'reduce_wwPDB_het_dict.txt')

# Configuration
THREADS = os.cpu_count() or 4
