
import sys
import os
import numpy as np

def create_gridbox_pdb(center, size, output_file="gridbox.pdb"):
    """
    Creates a PDB file with 8 atoms representing the corners of the gridbox.
    """
    x, y, z = center
    dx, dy, dz = size
    
    # Half dimensions
    hx, hy, hz = dx/2, dy/2, dz/2
    
    # 8 Corners
    corners = [
        (x - hx, y - hy, z - hz),
        (x - hx, y - hy, z + hz),
        (x - hx, y + hy, z - hz),
        (x - hx, y + hy, z + hz),
        (x + hx, y - hy, z - hz),
        (x + hx, y - hy, z + hz),
        (x + hx, y + hy, z - hz),
        (x + hx, y + hy, z + hz),
    ]
    
    with open(output_file, 'w') as f:
        f.write("REMARK    GENERATED BY CREATE_BOX_PDB.PY\n")
        f.write(f"REMARK    CENTER: {center}\n")
        f.write(f"REMARK    SIZE:   {size}\n")
        
        for i, (cx, cy, cz) in enumerate(corners):
            # Atom, ID, Name, Res, Chain, ResID, X, Y, Z, Occupancy, TempFactor
            # HETATM    1  C   BOX A   1      49.594  38.266 128.533  1.00  0.00           C
            # Using Helium (HE) or Carbon (C) for visibility.
            f.write(f"HETATM{i+1:5d}  C   BOX A   1    {cx:8.3f}{cy:8.3f}{cz:8.3f}  1.00  0.00           C  \n")
            
        # Optional: CONECT records to draw lines (cube edges)
        # 1-2, 1-3, 1-5
        # 2-4, 2-6
        # 3-4, 3-7
        # 4-8
        # 5-6, 5-7
        # 6-8
        # 7-8
        connections = [
            (1, 2), (1, 3), (1, 5),
            (2, 4), (2, 6),
            (3, 4), (3, 7),
            (4, 8),
            (5, 6), (5, 7),
            (6, 8),
            (7, 8)
        ]
        for start, end in connections:
             f.write(f"CONECT{start:5d}{end:5d}\n")
             
    print(f"Created {output_file}")


if __name__ == "__main__":
    # If args provided: xc yc zc xs ys zs
    if len(sys.argv) == 7:
        try:
            xc, yc, zc = float(sys.argv[1]), float(sys.argv[2]), float(sys.argv[3])
            xs, ys, zs = float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6])
            create_gridbox_pdb((xc, yc, zc), (xs, ys, zs))
        except ValueError:
            print("Invalid numeric arguments.")
    else:
        print("Usage: python create_box_pdb.py xc yc zc xs ys zs")
        print("Example (from recent log):")
        print("python create_box_pdb.py 49.594 38.266 128.533 39.832 35.81 32.832")
